staging-settings:
  user-workflow:
    workflow-name: "rwa-verification"
  workflow-artifacts:
    workflow-path: "./workflows/rwa-verification.ts"

production-settings:
  user-workflow:
    workflow-name: "rwa-verification"
  workflow-artifacts:
    workflow-path: "./workflows/rwa-verification.ts"
